In [22]:
import pickle
import numpy as np
import nibabel as nib

In [7]:
box_sp = "/scratch/01/ahrasoulian/projects/nnDetection/models/Task100_PRL/RetinaUNetV001_D3V001_3d/fold0/test_predictions/case_00070_boxes.pkl"
with open(box_sp, "rb") as f:
    boxes = pickle.load(f)

boxes

{'pred_boxes': array([[ 42.178093, 107.28867 ,  45.199158, 117.49149 , 126.00381 ,
         135.38632 ],
        [ 45.497986, 122.60827 ,  48.613014, 132.67241 , 176.67738 ,
         187.92842 ],
        [ 47.793926, 140.9714  ,  50.828472, 149.21243 , 135.96771 ,
         143.52522 ],
        ...,
        [ 43.835938, 128.      ,  47.226562, 133.125   , 176.3125  ,
         185.875   ],
        [ 54.3125  , 111.625   ,  57.21875 , 119.375   , 210.25    ,
         217.4375  ],
        [ 14.40625 ,  43.75    ,  17.09375 ,  51.75    ,  93.90625 ,
          99.125   ]], shape=(569, 6), dtype=float32),
 'pred_scores': array([0.9278443 , 0.915534  , 0.77105975, 0.12328175, 0.30864254,
        0.02166748, 0.0181071 , 0.0300787 , 0.01402791, 0.01402791,
        0.06336455, 0.01393636, 0.02466311, 0.01333618, 0.02514632,
        0.01310221, 0.05379865, 0.01301066, 0.02516683, 0.01210531,
        0.02289623, 0.01191203, 0.02337424, 0.01165771, 0.01121012,
        0.01115926, 0.01109823, 0.02205

In [5]:
mask_sp = "/scratch/01/ahrasoulian/projects/nnDetection/models/Task100_PRL/RetinaUNetV001_D3V001_3d/fold0/test_predictions/case_00070_seg.pkl"
with open(mask_sp, "rb") as f:
    mask = pickle.load(f)

mask

{'pred_seg': array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..

In [8]:
boxes['pred_boxes']

array([[ 42.178093, 107.28867 ,  45.199158, 117.49149 , 126.00381 ,
        135.38632 ],
       [ 45.497986, 122.60827 ,  48.613014, 132.67241 , 176.67738 ,
        187.92842 ],
       [ 47.793926, 140.9714  ,  50.828472, 149.21243 , 135.96771 ,
        143.52522 ],
       ...,
       [ 43.835938, 128.      ,  47.226562, 133.125   , 176.3125  ,
        185.875   ],
       [ 54.3125  , 111.625   ,  57.21875 , 119.375   , 210.25    ,
        217.4375  ],
       [ 14.40625 ,  43.75    ,  17.09375 ,  51.75    ,  93.90625 ,
         99.125   ]], shape=(569, 6), dtype=float32)

In [12]:
np.unique(mask['pred_seg']), mask['pred_seg'].sum()

(array([0, 1], dtype=uint8), np.uint64(110))

In [30]:
# nnUNet
mask_infop = "/scratch/04/public_datasets/nnUNet_predictions/case_00642.pkl"
mask_np = "/scratch/04/public_datasets/nnUNet_predictions/case_00642.npz"
mask_nii = "/scratch/04/public_datasets/nnUNet_predictions/case_00642.nii.gz"
with open(mask_infop, "rb") as f:
    mask_info = pickle.load(f)

with np.load(mask_np) as data:
    # Print the list of all array keys within the file
    print("Keys in the NPZ file:", data.files)
    print(np.unique(data['softmax']))
    print(data['softmax'].shape)
    print(data['softmax'][:, 10, 10, 10])

np.unique(nib.load(mask_nii).get_fdata())


Keys in the NPZ file: ['softmax']
[0.000e+00 5.960e-08 1.192e-07 ... 9.990e-01 9.995e-01 1.000e+00]
(2, 90, 320, 320)
[1. 0.]


array([0., 1.])