In [2]:
import pickle
import numpy as np
import nibabel as nib
import torch
import os

In [3]:
root_path = "/scratch/04/public_datasets/nnDet/Task100_PRL/"
with open(os.path.join(root_path, "preprocessed", "splits_final.pkl"), "rb") as f:
    splits = pickle.load(f)

splits

[OrderedDict([('train',
               array(['case_00002', 'case_00003', 'case_00004', 'case_00007',
                      'case_00009', 'case_00011', 'case_00012', 'case_00013',
                      'case_00017', 'case_00019', 'case_00020', 'case_00021',
                      'case_00022', 'case_00023', 'case_00025', 'case_00026',
                      'case_00028', 'case_00029', 'case_00030', 'case_00032',
                      'case_00033', 'case_00035', 'case_00036', 'case_00037',
                      'case_00038', 'case_00039', 'case_00041', 'case_00042',
                      'case_00044', 'case_00045', 'case_00046', 'case_00047',
                      'case_00048', 'case_00050', 'case_00051', 'case_00054',
                      'case_00056', 'case_00057', 'case_00059', 'case_00061',
                      'case_00062', 'case_00063', 'case_00065', 'case_00066',
                      'case_00067', 'case_00068', 'case_00071', 'case_00074',
                      'case_00076', 'cas

In [8]:
cp = torch.load("/scratch/01/ahrasoulian/projects/CondInst3d-PRL/scripts/outputs/condinst3d-prl-final/2026-02-21_00-58-25/tb/version_0/checkpoints/last.ckpt", weights_only=False, map_location="cpu")
print(cp.keys())
cp['epoch']

dict_keys(['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'loops', 'callbacks', 'optimizer_states', 'lr_schedulers', 'hparams_name', 'hyper_parameters', 'datamodule_hparams_name', 'datamodule_hyper_parameters'])


999

In [ ]:
box_sp = "/scratch/01/ahrasoulian/projects/nnDetection/models/Task100_PRL/RetinaUNetV001_D3V001_3d/fold0/test_predictions/case_00070_boxes.pkl"
with open(box_sp, "rb") as f:
    boxes = pickle.load(f)

boxes

In [5]:
mask_sp = "/scratch/01/ahrasoulian/projects/nnDetection/models/Task100_PRL/RetinaUNetV001_D3V001_3d/fold0/test_predictions/case_00070_seg.pkl"
with open(mask_sp, "rb") as f:
    mask = pickle.load(f)

mask

{'pred_seg': array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..

In [8]:
boxes['pred_boxes']

array([[ 42.178093, 107.28867 ,  45.199158, 117.49149 , 126.00381 ,
        135.38632 ],
       [ 45.497986, 122.60827 ,  48.613014, 132.67241 , 176.67738 ,
        187.92842 ],
       [ 47.793926, 140.9714  ,  50.828472, 149.21243 , 135.96771 ,
        143.52522 ],
       ...,
       [ 43.835938, 128.      ,  47.226562, 133.125   , 176.3125  ,
        185.875   ],
       [ 54.3125  , 111.625   ,  57.21875 , 119.375   , 210.25    ,
        217.4375  ],
       [ 14.40625 ,  43.75    ,  17.09375 ,  51.75    ,  93.90625 ,
         99.125   ]], shape=(569, 6), dtype=float32)

In [12]:
np.unique(mask['pred_seg']), mask['pred_seg'].sum()

(array([0, 1], dtype=uint8), np.uint64(110))

In [30]:
# nnUNet
mask_infop = "/scratch/04/public_datasets/nnUNet_predictions/case_00642.pkl"
mask_np = "/scratch/04/public_datasets/nnUNet_predictions/case_00642.npz"
mask_nii = "/scratch/04/public_datasets/nnUNet_predictions/case_00642.nii.gz"
with open(mask_infop, "rb") as f:
    mask_info = pickle.load(f)

with np.load(mask_np) as data:
    # Print the list of all array keys within the file
    print("Keys in the NPZ file:", data.files)
    print(np.unique(data['softmax']))
    print(data['softmax'].shape)
    print(data['softmax'][:, 10, 10, 10])

np.unique(nib.load(mask_nii).get_fdata())


Keys in the NPZ file: ['softmax']
[0.000e+00 5.960e-08 1.192e-07 ... 9.990e-01 9.995e-01 1.000e+00]
(2, 90, 320, 320)
[1. 0.]


array([0., 1.])

In [6]:
nndet_plan = "/scratch/01/ahrasoulian/projects/nnDetection/models/Task100_PRL/RetinaUNetV001_D3V001_3d/fold0/plan.pkl"

with open(nndet_plan, "rb") as f:
    plan = pickle.load(f)

plan.keys()

dict_keys(['mode', 'target_spacing', 'normalization_schemes', 'use_mask_for_norm', 'anisotropy_threshold', 'resample_anisotropy_threshold', 'target_spacing_percentile', 'dim', 'num_modalities', 'all_classes', 'num_classes', 'transpose_forward', 'transpose_backward', 'dataset_properties', 'planner_id', 'network_dim', 'dataloader_kwargs', 'data_identifier', 'postprocessing', 'patch_size', 'batch_size', 'architecture', 'anchors', 'target_spacing_transposed', 'median_shape_transposed', 'do_dummy_2D_data_aug', 'trigger_lr1'])

In [8]:
plan['patch_size'], plan['batch_size']

(array([ 56, 192, 128]), 4)

In [9]:
plan['architecture']

{'arch_name': 'RetinaUNetV001',
 'max_channels': 320,
 'start_channels': 32,
 'fpn_channels': 128,
 'head_channels': 128,
 'classifier_classes': 1,
 'seg_classes': 1,
 'in_channels': 4,
 'dim': 3,
 'class_weight': [0.5, 0.0],
 'conv_kernels': [[1, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3]],
 'strides': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]],
 'decoder_levels': (2, 3, 4, 5)}

In [10]:
plan['anchors']

{'width': [(np.float64(6.0), np.float64(4.0), np.float64(10.0)),
  (np.float64(12.0), np.float64(8.0), np.float64(20.0)),
  (np.float64(24.0), np.float64(16.0), np.float64(40.0)),
  (np.float64(24.0), np.float64(16.0), np.float64(40.0))],
 'height': [(np.float64(11.0), np.float64(8.0), np.float64(14.0)),
  (np.float64(22.0), np.float64(16.0), np.float64(28.0)),
  (np.float64(44.0), np.float64(32.0), np.float64(56.0)),
  (np.float64(88.0), np.float64(64.0), np.float64(112.0))],
 'depth': [(np.float64(8.0), np.float64(10.0), np.float64(13.0)),
  (np.float64(16.0), np.float64(20.0), np.float64(26.0)),
  (np.float64(32.0), np.float64(40.0), np.float64(52.0)),
  (np.float64(64.0), np.float64(80.0), np.float64(104.0))],
 'stride': 1}

In [12]:
plan['trigger_lr1'], plan['normalization_schemes']

(False, OrderedDict([(0, 'nonCT'), (1, 'nonCT'), (2, 'nonCT'), (3, 'nonCT')]))